on: [push]

jobs:
  BUILD:
    runs-on: [ubuntu-latest]
    steps:
      - run: git init
      - run: git remote -v
      - run: git remote add origin master https://grandalf6:${{ secrets.GITHUB_TOKEN}}@github.com/balbinasurma/test.git