on:
  push:
    branches: 
      - code

jobs:
  BUILD:
    runs-on: [ubuntu-latest]
    steps:
      - run: git init
      - run: git remote add origin https://grandalf6:${{ secrets.GITHUB_TOKEN}}@github.com/balbinasurma/test.git
      - run: git checkout -b auto
      - run: echo "auto" > auto.html
      - run: git add .
      - run: git config user.email grandalf6@gmail.com
      - run: git config user.email
      - run: git config user.name grandalf6
      - run: git config user.name
      - run: git commit -m "autoCommit"
      - run: git push --set-upstream origin auto