on: [push]

jobs:
  BUILD:
    runs-on: [ubuntu-latest]
    steps:
      - run: git init
      - run: git remote -v
      - run: git remote set-url --push origin https://grandalf6:${{ GITHUB_TOKEN}}@github.com/balbinasurma/test.git